service: landet-backend
useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentBucket: landet-bucket
  role: ${env:IAM_ROLE}
  environment:
    USERS_TABLE: ${env:USERS_TABLE}
    BOOKINGS_TABLE: ${env:BOOKINGS_TABLE}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  login:
    handler: endpoints/login.handler
    events:
      - http:
          path: login
          method: POST
  bookings:
    handler: endpoints/bookings.handler
    events:
      - http:
          path: bookings
          method: GET
  booking:
    handler: endpoints/booking.handler
    events:
      - http:
          path: booking
          method: POST

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH

    BookingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookings-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: familyId
            AttributeType: S
          - AttributeName: bookingId
            AttributeType: S
        KeySchema:
          - AttributeName: familyId
            KeyType: HASH
          - AttributeName: bookingId
            KeyType: RANGE