service: landet-backend
useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentBucket: landet-bucket
  role: ${env:IAM_ROLE}

  environment:
    USERS_TABLE: ${env:USERS_TABLE}
    BOOKINGS_TABLE: ${env:BOOKINGS_TABLE}
    JWT_SECRET: ${env:JWT_SECRET}

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
      allowCredentials: true

functions:
  login:
    handler: endpoints/login.handler
    events:
      - httpApi:
          path: /login
          method: post

  getBookings:
    handler: endpoints/getBookings.handler
    events:
      - httpApi:
          path: /bookings
          method: get

  createBooking:
    handler: endpoints/createBooking.handler
    events:
      - httpApi:
          path: /booking
          method: post

  deleteBooking:
    handler: endpoints/deleteBooking.handler
    events:
      - httpApi:
          path: /bookings/{bookingId}
          method: delete

  updateBooking:
    handler: endpoints/updateBooking.handler
    events:
      - httpApi:
          path: /bookings/{bookingId}
          method: put

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH

    BookingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: bookings-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: familyId
            AttributeType: S
          - AttributeName: bookingId
            AttributeType: S
        KeySchema:
          - AttributeName: familyId
            KeyType: HASH
          - AttributeName: bookingId
            KeyType: RANGE